steps:
  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        pip3 install --upgrade pip
        pip3 install -r Announcements/requirements.txt
        SLACK_TOKEN=$(gcloud secrets versions access latest --secret="slack-token")
        gcloud functions deploy post_message_to_slack_http \
          --region europe-west1 \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars SLACK_TOKEN=$$SLACK_TOKEN \
          --entry-point post_message_to_slack \
          --source=Announcements \
          --service-account cloud-build-sa@charged-sector-427921-v5.iam.gserviceaccount.com

  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        pip3 install --upgrade pip
        pip3 install -r Invoicing/requirements.txt
        HARVEST_API_KEY=$(gcloud secrets versions access latest --secret="harvest-api-key")
        HARVEST_ACC_ID=$(gcloud secrets versions access latest --secret="harvest-acc-id")
        gcloud functions deploy create_invoices_http \
          --region europe-west1 \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars HARVEST_API_KEY=$$HARVEST_API_KEY,HARVEST_ACCOUNT_ID=$$HARVEST_ACC_ID \
          --entry-point invoicing_trigger \
          --source=Invoicing \
          --service-account cloud-build-sa@charged-sector-427921-v5.iam.gserviceaccount.com

  - name: 'google/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y python3 python3-pip
        pip3 install --upgrade pip
        pip3 install -r Payroll/requirements.txt
        DEEL_API_KEY=$(gcloud secrets versions access latest --secret="deel-api-key")
        HARVEST_API_KEY=$(gcloud secrets versions access latest --secret="harvest-api-key")
        HARVEST_ACC_ID=$(gcloud secrets versions access latest --secret="harvest-acc-id")
        gcloud functions deploy process_payroll_http \
          --region europe-west1 \
          --runtime python311 \
          --trigger-http \
          --allow-unauthenticated \
          --set-env-vars DEEL_API_KEY=$$DEEL_API_KEY,HARVEST_API_KEY=$$HARVEST_API_KEY,HARVEST_ACCOUNT_ID=$$HARVEST_ACC_ID \
          --entry-point payroll_trigger \
          --source=Payroll \
          --service-account cloud-build-sa@charged-sector-427921-v5.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1600s
